name: CI CD

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies, build
      run: |
        npm install
        npm run build
        
    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
        
  deploy:
    needs: build
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: download artifact
      uses: actions/download-artifact@master
      with:
        name: build
      
    - name: deploy to S3
      uses: actions/aws/cli@master
      with:
        args: s3 cp build s3://sunyang9876-aws/ --recursive
      env:
        AWS_DEFAULT_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
<<<<<<< HEAD
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
=======
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
>>>>>>> 49d98fc3955148bb36f5efc27a1188eb1e36f330
